### ISSUE TITLE
Different files for each CSS parts

### ISSUE THREAD

**Issue by anna-dominguez** [Vesta-nna/AnnaDominguez_2_12042021#9]
# Description

- Make files of defined CSS parts for example header, main, and footer
- Regroup the display part of the flexbox and grids

# To-do

- [ ]  File of page display
- [ ]  File of header
- [ ]  File of main
- [ ]  File of footer
